import os
from src.models import TaskArtifact

PUBLIC_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), 'public', 'downloads')

def ensure_public_dir():
    if not os.path.exists(PUBLIC_DIR):
        os.makedirs(PUBLIC_DIR)

def DocumentGenerator(artifact: TaskArtifact) -> str:
    """
    Generates a Markdown file for the trip and returns the relative download link.
    """
    print(f"--- Tool: DocumentGenerator Executed for {artifact.trip_id} ---")
    ensure_public_dir()
    
    filename = f"{artifact.trip_id}_Guide.md"
    filepath = os.path.join(PUBLIC_DIR, filename)
    
    content = f"""# Travel Guide: {artifact.trip_id}

## Itinerary
"""
    for item in artifact.itinerary_timeline:
        content += f"- **{item['time']}**: {item['event']}\n"
        
    content += f"""
## Conflict Resolutions
"""
    for conflict in artifact.conflict_resolutions:
        content += f"- **Issue**: {conflict.original_conflict}\n  **Fix**: {conflict.recommended_action}\n"
        
    content += f"""
## Packing & Tips
- **Weather**: {artifact.packing_inputs.weather_summary}
- **Activities**: {', '.join(artifact.packing_inputs.activities_tags)}
- **Compliance**: {', '.join(artifact.packing_inputs.compliance_tags)}

*Generated by Rahagir AI*
"""

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
        
    return f"/static/downloads/{filename}"
